Repository YAPP-Github/20th-ALL-Rounder-Team-1-Web, pull requests merged in 2022-06, with the labels that each got.

#59 [Weekand-1024] 새롭게 추가된 색상 반영
  src/style/styled.d.ts
  src/style/theme.ts
Labels: :art: 스타일

#61 [Weekand-1021] 기존 모달이라 생각된 요소 팝업으로 수정
  public/index.html
  src/App.tsx
  src/ModalPortal.tsx
  src/PopUpPortal.tsx
  src/components/common/DimmedLayer.tsx
  src/components/common/Modal.tsx
  src/components/common/PopUp.tsx
  src/components/common/index.ts
  src/contexts/DimmedLayerContext.tsx
  src/contexts/PopUpContext.tsx
  src/contexts/index.ts
Labels: :bug: 버그

#65 [Weekand-1026] styled component 타입 수정
  src/style/styled.d.ts
  src/style/theme.ts
Labels: :bug: 버그

#63 [Weekand-1023] graphQL 기본 세팅
  package.json
  src/index.tsx
  yarn.lock
Labels: :sparkles: 기능

#62 [Weekand-1016] 각 페이지를 lazy load, [Weekand-1022] 전체적인 페이지 구성 (react-router-dom 사용)
  package.json
  src/App.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/index.ts
  yarn.lock
Labels: :sparkles: 기능

#67 [Weekand-1027] 폰트 스타일 추가 및 폰트 색상을 인자로 받을 수 있는 형태로 변경
  src/style/styled.d.ts
  src/style/theme.ts
Labels: :art: 스타일

#78 [Weekand-1028] 로그인 페이지
  package.json
  src/assets/smiling_emoji.png
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/components/common/PageLayout.tsx
  src/pages/Login.tsx
  src/style/styled.d.ts
  src/style/theme.ts
  yarn.lock
Labels: :art: 스타일, :sparkles: 기능

#77 [Weekand-1035] JobSelection 컴포넌트 디자인에 맞게 수정
  src/components/common/Interest.tsx
  src/components/common/JobSelection.tsx
Labels: :art: 스타일, :recycle: 리팩토링

#81 [Weekand-1037] 관심사 최대 3개만 선택되도록 수정
  src/components/common/Interest.tsx
Labels: :bug: 버그

#85 [Weekand-1038] 폰트명 수정
  src/pages/Login.tsx
  src/style/styled.d.ts
  src/style/theme.ts
Labels: :recycle: 리팩토링

#87 [Weekand-1039] 배포 방식 변경으로 인해 불필요해진 파일들 제거
  .dockerignore
  .github/workflows/main.yml
  Dockerfile
  nginx.conf
Labels: :recycle: 리팩토링

#68 [Weekand-1017] 모달에 들어갈 캘린더 만들기
  package.json
  src/components/calender/Calender.tsx
  src/components/calender/CalenderBody.tsx
  src/components/calender/CalenderHeader.tsx
  src/components/calender/index.ts
  src/hooks/index.ts
  src/hooks/useDate.tsx
  yarn.lock
Labels: :sparkles: 기능

#83 [Weekand-1029] 비밀번호 찾기 페이지
  src/App.tsx
  src/components/common/Input.tsx
  src/pages/FindPassword.tsx
  src/pages/Login.tsx
  src/pages/index.ts
Labels: :art: 스타일, :sparkles: 기능

#82 [Weekand-1033] 친구 리스트 가로 스크롤
  src/assets/story_left_button.png
  src/assets/story_right_button.png
  src/components/common/FriendStories.tsx
  src/components/common/FriendStory.tsx
  src/components/common/index.ts
  src/utils/dummyData.ts
  src/utils/index.ts
  src/utils/story.ts
Labels: :sparkles: 기능

#79 [Weekand-1031] 관심사 선택 페이지
  src/components/common/Interest.tsx
  src/components/common/index.ts
  src/pages/SelectInterest.tsx
  src/pages/index.ts
  src/utils/dummyData.ts
Labels: :sparkles: 기능

#102 [Weekand-1049] 스프라이트 이미지 적용
  src/assets/css_sprites.png
  src/pages/Login.tsx
Labels: :art: 스타일, :sparkles: 기능

#98 [Weekand-1046] 설정 페이지 : 접근성 설정
  src/components/common/Accessibility.tsx
  src/components/common/index.ts
  src/style/theme.ts
Labels: :sparkles: 기능

#105 [Weekand-1051] 로그인 페이지 UI 개발 완성
  src/pages/Login.tsx
Labels: :sparkles: 기능

#107 [Weekand-1052] import 구문 정리를 위한 플러그인 추가
  .eslintrc.js
  package.json
  src/App.tsx
  src/components/calender/Calender.tsx
  src/components/calender/CalenderBody.tsx
  src/components/layout/ModalLayout.tsx
  src/contexts/SettingContext.tsx
  src/hooks/useDate.tsx
  src/index.tsx
  src/pages/Login.tsx
  src/style/theme.ts
  yarn.lock
Labels: :sparkles: 기능, :recycle: 리팩토링

#108 [Weekand-1050] 카테고리 페이지 생성
  src/App.tsx
  src/common/index.ts
  src/contexts/SettingContext.tsx
  src/hooks/index.ts
  src/hooks/useContextMenu.tsx
  src/pages/home/components/FriendStories.tsx
  src/pages/home/components/FriendStory.tsx
  src/pages/home/components/index.ts
  src/pages/index.ts
  src/pages/manageCategory/components/Category.tsx
  src/pages/manageCategory/components/CategoryList.tsx
  src/pages/manageCategory/components/CategorySubMenu.tsx
  src/pages/manageCategory/components/index.ts
  src/pages/manageCategory/index.tsx
  src/pages/setting/components/Accessibility.tsx
  src/pages/setting/components/EditProfile.tsx
  src/pages/setting/components/Question.tsx
  src/pages/setting/components/index.ts
  src/style/GlobalStyle.ts
  src/utils/dummyData.ts
  src/utils/getCurrentSetting.tsx
Labels: :sparkles: 기능

#118 [Weekand-1058] ES6 관련 코드 작성 안되던 오류 수정
  package.json
  yarn.lock
Labels: :bug: 버그

#120 [Weekand-1041] 이용 약관 동의 페이지
  public/index.html
  src/App.tsx
  src/common/Button.tsx
  src/pages/agreement/index.tsx
  src/pages/index.ts
Labels: :bug: 버그, :sparkles: 기능

#115 [Weekand-1055] 세팅 페이지 컴포넌트 전환 방법 수정
  src/contexts/SettingContext.tsx
  src/contexts/index.ts
  src/index.tsx
  src/pages/setting/components/SettingMenu.tsx
  src/pages/setting/components/SettingSidebar.tsx
  src/pages/setting/index.tsx
  src/utils/index.ts
  src/utils/setting.tsx
Labels: :sparkles: 기능

#119 [Weekand-1057] 설정 페이지 : 프로필 편집
  src/common/Interest.tsx
  src/common/index.ts
  src/common/layout/PageLayout.tsx
  src/pages/selectInterest/components/Interest.tsx
  src/pages/selectInterest/components/index.ts
  src/pages/selectInterest/index.tsx
  src/pages/setting/components/EditProfile.tsx
  src/pages/setting/components/ProfileInfo.tsx
  src/pages/setting/components/Question.tsx
  src/pages/setting/components/index.ts
  src/pages/setting/index.tsx
  src/utils/dummyData.ts
  src/utils/validation.ts
Labels: :sparkles: 기능

#140 [Weekand-1072] 배경 색이 정상적으로 변경되지 않는 이슈
  src/App.tsx
  src/common/layout/PageLayout.tsx
  src/hooks/index.ts
  src/hooks/useBackgroundColor.tsx
  src/utils/background.ts
  src/utils/index.ts
Labels: :bug: 버그, :sparkles: 기능, :recycle: 리팩토링

#138 [Weekand-1071] 새로워진 스프라이트 이미지 적용
  src/assets/css_sprites.png
  src/pages/agreement/index.tsx
  src/pages/login/index.tsx
  src/pages/register/components/ValidationControlledInput.tsx
Labels: :art: 스타일, :sparkles: 기능

#88 [Weekand-1032] 헤더 완성
  src/App.tsx
  src/assets/pororo.jpeg
  src/assets/setting_right_button.png
  src/assets/story_left_button.png
  src/assets/story_right_button.png
  src/assets/weekand_logo.png
  src/common/Alarm.tsx
  src/common/AlarmList.tsx
  src/common/Header.tsx
  src/common/index.ts
  src/common/layer/DimmedLayer.tsx
  src/common/layout/PageLayout.tsx
  src/contexts/DimmedLayerContext.tsx
  src/pages/agreement/index.tsx
  src/pages/findPassword/index.tsx
  src/pages/home/components/FriendStories.tsx
  src/pages/home/index.tsx
  src/pages/index.ts
  src/pages/login/index.tsx
  src/pages/manageCategory/index.tsx
  src/pages/register/index.tsx
  src/pages/search/index.tsx
  src/pages/selectInterest/index.tsx
  src/pages/setting/index.tsx
  src/utils/dummyData.ts
Labels: :sparkles: 기능

#142 [Weekand-1062] 메타 정보 적용
  public/index.html
  src/App.tsx
  src/assets/favicon.png
  src/hooks/index.ts
  src/hooks/useDocumentTitle.tsx
Labels: :sparkles: 기능

#146 [Weekand-1075] background color 목록 추가
  src/hooks/useBackgroundColor.tsx
Labels: :bug: 버그

#148 [Weekand-1076] og: image url 변경
  public/index.html
Labels: :sparkles: 기능
