Repository YAPP-Github/20th-ALL-Rounder-Team-1-Web, pull requests merged in 2022-05, with the labels that each got.

#1 기본 웹팩 설정
  .prettierignore
  dongkyun/.babelrc.js
  dongkyun/.gitignore
  dongkyun/.prettierrc
  dongkyun/package.json
  dongkyun/public/index.html
  dongkyun/src/App.tsx
  dongkyun/src/assets/pororo.jpeg
  dongkyun/src/index.tsx
  dongkyun/tsconfig.json
  dongkyun/webpack.common.js
  dongkyun/webpack.dev.js
  dongkyun/webpack.prod.js
  dongkyun/yarn.lock
Labels: enhancement

#3 프로젝트 기본 설정
  soodong/.babelrc
  soodong/.gitignore
  soodong/package-lock.json
  soodong/package.json
  soodong/public/index.html
  soodong/src/App.tsx
  soodong/src/index.tsx
  soodong/tsconfig.json
  soodong/webpack.common.js
  soodong/webpack.dev.js
  soodong/webpack.prod.js
Labels: enhancement

#8 프로젝트 초기 세팅 완료
  .babelrc.js
  .gitignore
  .prettierrc
  dongkyun/.babelrc.js
  dongkyun/.gitignore
  dongkyun/package.json
  dongkyun/src/App.tsx
  dongkyun/src/index.tsx
  dongkyun/tsconfig.json
  dongkyun/yarn.lock
  package-lock.json
  package.json
  public/index.html
  soodong/.babelrc
  soodong/.gitignore
  soodong/public/index.html
  soodong/src/index.tsx
  soodong/tsconfig.json
  soodong/webpack.common.js
  soodong/webpack.dev.js
  soodong/webpack.prod.js
  src/App.tsx
  src/assets/pororo.jpeg
  src/index.tsx
  tsconfig.json
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
  yarn.lock
Labels: enhancement

#12 ✨ npm 사용시 에러 발생 시키기
  .npmrc
  package.json
  tsconfig.json
Labels: :gear: 설정

#13 ✨ 린트와 허스키 설정 추가
  .babelrc.js
  .eslintrc.js
  package.json
  yarn.lock
Labels: :gear: 설정, :recycle: 리팩토링

#15 ✨ CI/CD를 위한 github actions 구성
  .github/workflows/main.yml
Labels: :gear: 설정

#17 ✨ 도커 설정 추가와 포트 번호 수정
  .dockerignore
  .github/workflows/main.yml
  Dockerfile
Labels: :gear: 설정

#18 ✨ 폴더 구조 확립
  .gitignore
  README.md
  src/api/index.ts
  src/components/index.ts
  src/hooks/index.ts
  src/pages/index.ts
  src/types/index.ts
  src/utils/index.ts
Labels: :sparkles: 기능

#20 :sparkles: PR 생성시 빌드 테스트 추가
  .github/workflows/build_test.yml
  package-lock.json
Labels: :gear: 설정

#32 :bug: package-lock 파일 재작성
  package-lock.json
Labels: :bug: 버그

#34 :sparkles: @babel/preset-typescript 요소 추가
  .babelrc.js
  package.json
  yarn.lock
Labels: :gear: 설정

#22 ✨ 이슈 템플릿 작성
  .github/ISSUE_TEMPLATE/issue--bug-template.md
  .github/ISSUE_TEMPLATE/issue--feature-template.md
Labels: :gear: 설정

#36 :bug: 절대 경로 세팅 수정
  tsconfig.json
Labels: :gear: 설정

#39 [Weekand-1002, Weekand-1003] reset.css 구성 및 전역 css 설정
  .eslintrc.js
  package.json
  src/index.tsx
  src/style/GlobalStyle.ts
  src/style/index.ts
  src/style/reset.ts
  src/style/styled.d.ts
  src/style/theme.ts
  yarn.lock
Labels: :art: 스타일

#41 [Weekand-1005] [공통 컴포넌트] 버튼 컴포넌트 만들기
  src/components/common/Button.tsx
Labels: :sparkles: 기능

#43 [Weekand-1013] 폰트 설정
  src/style/GlobalStyle.ts
  src/style/reset.ts
Labels: :art: 스타일, :sparkles: 기능

#38 [Weekand-1006] [공통 컴포넌트] 인풋 컴포넌트 만들기
  src/components/common/Input.tsx
  src/components/index.ts
  src/utils/index.ts
  src/utils/validation.ts
Labels: :sparkles: 기능

#37 [Weekand-1004, Weekand-1008] [공통 컴포넌트] 팝업 컴포넌트 만들기, 딤드레이어 만들기
  public/index.html
  src/App.tsx
  src/ModalPortal.tsx
  src/components/common/CalendarPopUp.tsx
  src/components/common/FindPasswordPopUp.tsx
  src/components/common/Modal.tsx
  src/components/index.ts
  src/contexts/PopUpContext.tsx
  src/contexts/index.ts
  src/index.tsx
  src/utils/AppProvider.tsx
  src/utils/index.ts
  yarn.lock
Labels: :sparkles: 기능

#51 [Weekand-1019] 디바운싱 인풋 사용을 위한 커스텀 훅 작성
  src/components/common/DebounceInput.tsx
  src/components/index.ts
Labels: :sparkles: 기능

#52 [Weekand-1014] Button 컴포넌트 rest props를 받을 수 있는 형태로 수정
  src/components/common/Button.tsx
Labels: :bug: 버그

#55 [Weekand-1007] 모달 컴포넌트 작성
  public/index.html
  src/App.tsx
  src/components/common/PageLayout.tsx
  src/components/common/index.ts
  src/components/index.ts
  src/components/layout/ModalLayout.tsx
  src/components/layout/index.ts
  src/style/GlobalStyle.ts
Labels: :sparkles: 기능

#53 [Weekand-1018] 필터 선택 공통 컴포넌트
  src/components/common/JobSelection.tsx
Labels: :sparkles: 기능
