Repository YAPP-Github/20th-ALL-Rounder-Team-1-Web, pull requests merged in 2022-07, with the labels that each got.

#150 [Weekand-1077] 관심사 선택 페이지 마크업 수정
  src/common/Interest.tsx
  src/pages/selectInterest/index.tsx
Labels: :art: 스타일

#152 [Weekand-1078] 회원가입 페이지 input validation 고도화
  src/pages/register/components/ValidationControlledInput.tsx
  src/pages/register/components/ValidationUncontrolledInput.tsx
  src/pages/register/index.tsx
  src/types/index.ts
Labels: :sparkles: 기능

#156 [Weekand-1080] 회원가입 플로우 자잘한 수정 반영
  src/App.tsx
  src/common/Interest.tsx
  src/common/layout/PageLayout.tsx
  src/hooks/useBackgroundColor.tsx
  src/pages/login/index.tsx
  src/pages/register/components/ValidationUncontrolledInput.tsx
  src/pages/register/index.tsx
Labels: :bug: 버그, :art: 스타일, :sparkles: 기능

#135 [Weekand-1048] 메인 페이지 : 일정 리스트
  src/pages/home/components/Schedule.tsx
  src/pages/home/components/Schedules.tsx
  src/pages/home/components/index.ts
  src/pages/home/index.tsx
  src/utils/dummyData.ts
Labels: :sparkles: 기능

#157 [Weekand-1042] 플로팅 버튼 작성
  src/App.tsx
  src/common/FloatingButton.tsx
  src/common/index.ts
  src/style/GlobalStyle.ts
Labels: :sparkles: 기능

#159 [Weekand-1081] 헤더 코드 개선
  src/common/Header.tsx
Labels: :sparkles: 기능, :recycle: 리팩토링

#161 [Weekand-1059] 메인 페이지 - 개인 프로필 컴포넌트
  src/pages/home/components/Profile.tsx
  src/pages/home/components/index.ts
Labels: :sparkles: 기능

#167 [Weekand-1085] 플로팅 버튼의 위치가 고정되도록 수정
  src/common/FloatingButton.tsx
Labels: :art: 스타일

#163 [Weekand-1083] 세팅페이지: 접근성 설정 컴포넌트 연결
  src/common/Interest.tsx
  src/pages/setting/components/Accessibility.tsx
  src/pages/setting/components/EditProfile.tsx
  src/pages/setting/components/Question.tsx
  src/pages/setting/components/SettingMenu.tsx
  src/pages/setting/components/SettingSidebar.tsx
  src/pages/setting/index.tsx
  src/utils/setting.tsx
Labels: :sparkles: 기능

#168 [Weekand-1082] 검색 페이지 - 친구 검색 페이지
  src/common/Interest.tsx
  src/common/index.ts
  src/common/search/CurrentCategoryList.tsx
  src/common/search/CurrentCategoryMenu.tsx
  src/common/search/CurrentCategoryMenus.tsx
  src/common/search/SearchBar.tsx
  src/common/search/index.ts
  src/pages/certainCategory/components/CurrentCategoryList.tsx
  src/pages/certainCategory/components/SearchBar.tsx
  src/pages/certainCategory/components/index.ts
  src/pages/certainCategory/index.tsx
  src/pages/search/components/FilterResult.tsx
  src/pages/search/components/SearchContent.tsx
  src/pages/search/components/SearchContents.tsx
  src/pages/search/components/SearchHistory.tsx
  src/pages/search/components/index.ts
  src/pages/search/index.tsx
  src/pages/setting/components/CurrentCategory.tsx
  src/pages/setting/components/CurrentCategoryMenu.tsx
  src/pages/setting/components/SearchBar.tsx
  src/pages/setting/components/index.ts
  src/utils/dummyData.ts
Labels: :sparkles: 기능

#173 [Weekand-1061] 메인페이지 - 달력 하단 부분 완성
  src/pages/home/components/Follow.tsx
  src/pages/home/components/Interest.tsx
  src/pages/home/components/Job.tsx
  src/pages/home/components/Purpose.tsx
  src/pages/home/components/index.ts
  src/pages/home/index.tsx
Labels: :sparkles: 기능

#176 [Weekand-1045] 설정 페이지: 비밀번호 변경
  src/common/Button.tsx
  src/common/index.ts
  src/common/input/Input.tsx
  src/common/input/ValidationControlledInput.tsx
  src/common/input/ValidationUncontrolledInput.tsx
  src/common/input/index.ts
  src/pages/register/index.tsx
  src/pages/setting/components/ChangePassword.tsx
  src/pages/setting/components/index.ts
  src/utils/setting.tsx
Labels: :sparkles: 기능, :recycle: 리팩토링

#177 [Weekand-1090] 메인 페이지 친구 스토리 목록 수정
  src/pages/home/components/FriendStories.tsx
  src/pages/home/components/FriendStory.tsx
  src/utils/dummyData.ts
Labels: :bug: 버그

#178 [Weekand-1091] 메뉴 우클릭 시 원하는 위치에 메뉴 나오지 않는 오류
  src/hooks/useContextMenu.tsx
  src/pages/manageCategory/components/Category.tsx
  src/pages/manageCategory/components/CategoryList.tsx
Labels: :bug: 버그

#179 [Weekand-1089] 회원가입 api 연결
  .eslintrc.js
  package.json
  src/api/index.ts
  src/api/register.tsx
  src/common/input/Input.tsx
  src/common/input/ValidationUncontrolledInput.tsx
  src/index.tsx
  src/pages/register/index.tsx
  src/pages/setting/components/EditProfile.tsx
  src/utils/validation.ts
  webpack.common.js
  yarn.lock
Labels: :sparkles: 기능

#181 [Weekand-1092] netlify에서 환경변수에 접근할 수 있도록 설정 추가
  webpack.common.js
Labels: :bug: 버그

#182 [Weekand-1088] 관심사 선택 api 연결
  src/App.tsx
  src/api/agreement.tsx
  src/api/index.ts
  src/common/input/Input.tsx
  src/contexts/RegisterContext.tsx
  src/contexts/index.ts
  src/index.tsx
  src/pages/agreement/index.tsx
  src/pages/register/index.tsx
  src/pages/selectInterest/index.tsx
Labels: :bug: 버그, :sparkles: 기능

#186 [Weekand-1095] 토스트 관련 코드 개선
  src/common/Toast.tsx
  src/contexts/ToastContext.tsx
Labels: :sparkles: 기능, :recycle: 리팩토링

#187 [Weekand-1093] 카테고리 페이지 api 연결
  src/api/category.tsx
  src/api/index.ts
  src/common/CategorySubMenu.tsx
  src/common/DebounceInput.tsx
  src/common/search/CurrentCategoryList.tsx
  src/common/search/CurrentCategoryMenu.tsx
  src/common/search/CurrentCategoryMenus.tsx
  src/common/search/SearchBar.tsx
  src/contexts/CategoryContext.tsx
  src/contexts/index.ts
  src/index.tsx
  src/pages/certainCategory/components/CurrentCategory.tsx
  src/pages/certainCategory/index.tsx
  src/pages/manageCategory/components/Category.tsx
  src/pages/manageCategory/components/CategoryList.tsx
  src/pages/search/index.tsx
  src/utils/constant.ts
  src/utils/index.ts
Labels: :sparkles: 기능

#188 [Weekand-1087] 로그인 api 연결
  src/api/agreement.ts
  src/api/index.ts
  src/api/login.ts
  src/api/register.ts
  src/pages/login/index.tsx
  src/utils/index.ts
  src/utils/storage.ts
Labels: :sparkles: 기능, :recycle: 리팩토링

#190 [Weekand-1096] 관심사 3개 이상 선택시 토스트 메시지 노출
  src/common/Interest.tsx
  src/pages/selectInterest/index.tsx
Labels: :sparkles: 기능

#193 [Weekand-1097] 임시 비밀번호 발급 페이지 토스트 구체화
  src/pages/getTempPassword/index.tsx
  src/utils/validation.ts
Labels: :bug: 버그

#194 [Weekand-1094] 검색 페이지 api 연결
  src/App.tsx
  src/api/search.tsx
  src/common/CategorySubMenu.tsx
  src/common/DebounceInput.tsx
  src/common/calender/Calender.tsx
  src/common/calender/CalenderHeader.tsx
  src/common/search/CurrentCategoryList.tsx
  src/common/search/SearchBar.tsx
  src/pages/certainCategory/index.tsx
  src/pages/index.ts
  src/pages/search/components/FilterResult.tsx
  src/pages/search/components/SearchContent.tsx
  src/pages/search/components/SearchContents.tsx
  src/pages/search/index.tsx
  src/pages/searchUser/components/Follow.tsx
  src/pages/searchUser/components/FriendStories.tsx
  src/pages/searchUser/components/FriendStory.tsx
  src/pages/searchUser/components/Interest.tsx
  src/pages/searchUser/components/Job.tsx
  src/pages/searchUser/components/Profile.tsx
  src/pages/searchUser/components/Purpose.tsx
  src/pages/searchUser/components/Schedule.tsx
  src/pages/searchUser/components/Schedules.tsx
  src/pages/searchUser/components/index.ts
  src/pages/searchUser/index.tsx
  src/utils/constant.ts
Labels: :sparkles: 기능

#196 [Weekand-1098] 알람 목록 api 연결
  src/api/category.ts
  src/api/notification.ts
  src/common/Alarm.tsx
  src/common/AlarmList.tsx
Labels: :sparkles: 기능

#198 [Weekand-1099] 카테고리 수정 팝업 작성
  src/App.tsx
  src/api/category.ts
  src/common/CategorySubMenu.tsx
  src/common/DebounceInput.tsx
  src/common/PopUp.tsx
  src/common/ProtectRoute.tsx
  src/common/index.ts
  src/common/input/Input.tsx
  src/common/layer/DimmedLayer.tsx
  src/common/popup/CategoryPopup.tsx
  src/common/popup/PopUp.tsx
  src/common/popup/index.ts
  src/common/search/CurrentCategoryList.tsx
  src/common/search/CurrentCategoryMenus.tsx
  src/contexts/CategoryContext.tsx
  src/contexts/DimmedLayerContext.tsx
  src/contexts/PopUpContext.tsx
  src/index.tsx
  src/models/index.ts
  src/pages/certainCategory/components/CurrentCategory.tsx
  src/pages/certainCategory/index.tsx
  src/pages/manageCategory/components/Category.tsx
  src/pages/manageCategory/components/CategoryList.tsx
  src/pages/search/index.tsx
  src/utils/category.ts
  src/utils/index.ts
Labels: :sparkles: 기능
